//! M7 — D-Bus client facades for the profile editor tab.
//!
//! These are thin typed wrappers over the proxies generated by
//! `zwhisper-ipc` (`Profiles1Proxy`, `Recorder1Proxy`). They exist
//! so the profile-tab logic can be unit-tested through small async
//! traits (`ReloadCall`, `GetRecording`) without spinning up a real
//! D-Bus broker.
//!
//! Both clients treat `ServiceUnknown` as the "daemon is offline"
//! case (M7-plan risk A4 / `DoD` `service_unknown_treated_as_daemon_off`)
//! rather than an error: the settings UI must remain usable even
//! when the daemon is not running, and the user simply gets a
//! "saved (will apply on next daemon start)" toast.
//!
//! Bus selection: session bus, mirroring the daemon (M3 lock-in).

// `ProfilesClient::connect` and `RecorderClient::connect` are
// constructed by `tabs::profile`'s save flow once Group D wires
// the live D-Bus path — until then the unit tests in this file
// (and in `tabs::profile`) are the only consumers, so clippy
// considers the helpers dead. See module doc for rationale.
#![allow(dead_code)]

use tracing::{debug, warn};
use zwhisper_ipc::{Profiles1Proxy, Recorder1Proxy};

use crate::error::SettingsError;

/// Outcome of a `Profiles1.reload` call. `DaemonOff` means the
/// well-known service name is unclaimed (`org.freedesktop.DBus.Error.ServiceUnknown`),
/// which the settings binary surfaces as a non-fatal toast rather
/// than a hard error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ReloadOutcome {
    Reloaded,
    DaemonOff,
}

/// Snapshot of the recorder state, simplified to a tri-state for
/// the save-during-recording prompt (`DoD` #3 / D6). Only the
/// `Recording` arm triggers the modal warning; transitional states
/// (`starting`, `stopping`, `failed`) and `Idle` are treated as
/// "safe to reload".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RecordingState {
    Idle,
    Recording,
    DaemonOff,
}

/// M8 — outcome of the pre-flight `ProtocolVersion` handshake. The
/// settings GUI runs this once on app load via [`probe_protocol`];
/// `Mismatch` switches the UI into a banner-only mode where every
/// action button is disabled and only the version mismatch is
/// shown.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ProtocolStatus {
    /// Daemon advertises the same `PROTOCOL_VERSION` as the
    /// settings binary. Normal operation.
    Match,
    /// Daemon is not on the bus. Same UX as M7's `DaemonOff` —
    /// the user sees a "Saved (daemon offline)" toast and the
    /// settings remain editable.
    DaemonOff,
    /// Daemon advertises a different version (or does not
    /// implement the property at all). UI must surface the banner
    /// and refuse every action.
    Mismatch {
        expected: String,
        got: String,
        legacy: bool,
    },
}

/// Probe the daemon's `Recorder1.ProtocolVersion` property and
/// classify the result. Lives next to the other client facades so
/// every D-Bus error mapping is in one place.
pub(crate) async fn probe_protocol() -> Result<ProtocolStatus, SettingsError> {
    let conn = zbus::Connection::session()
        .await
        .map_err(|e| SettingsError::Profile(format!("session bus: {e}")))?;
    let proxy = match Recorder1Proxy::new(&conn).await {
        Ok(p) => p,
        Err(zbus::Error::FDO(boxed)) => {
            if matches!(*boxed, zbus::fdo::Error::ServiceUnknown(_)) {
                return Ok(ProtocolStatus::DaemonOff);
            }
            return Err(SettingsError::Profile(format!("recorder proxy: {boxed}")));
        }
        Err(other) => {
            return Err(SettingsError::Profile(format!("recorder proxy: {other}")));
        }
    };
    match proxy.protocol_version().await {
        Ok(daemon_version) => {
            if daemon_version == zwhisper_ipc::PROTOCOL_VERSION {
                Ok(ProtocolStatus::Match)
            } else {
                Ok(ProtocolStatus::Mismatch {
                    expected: zwhisper_ipc::PROTOCOL_VERSION.to_owned(),
                    got: daemon_version,
                    legacy: false,
                })
            }
        }
        Err(e) if is_service_unknown(&e) => Ok(ProtocolStatus::DaemonOff),
        Err(zbus::Error::FDO(boxed)) => match *boxed {
            zbus::fdo::Error::UnknownMethod(_)
            | zbus::fdo::Error::UnknownProperty(_)
            | zbus::fdo::Error::UnknownInterface(_) => Ok(ProtocolStatus::Mismatch {
                expected: zwhisper_ipc::PROTOCOL_VERSION.to_owned(),
                got: zwhisper_ipc::ProtocolMismatch::LEGACY_DAEMON_SENTINEL.to_owned(),
                legacy: true,
            }),
            other => Err(SettingsError::Profile(format!(
                "protocol_version probe: {other}"
            ))),
        },
        Err(other) => Err(SettingsError::Profile(format!(
            "protocol_version probe: {other}"
        ))),
    }
}

/// Async port for `Profiles1.reload`. Lives as a trait so the save
/// logic in `tabs::profile` can be unit-tested with a fake that
/// records call counts without touching a live bus.
#[async_trait::async_trait]
pub(crate) trait ReloadCall: Send + Sync {
    async fn reload(&self) -> Result<ReloadOutcome, SettingsError>;
}

/// Async port for `Recorder1.GetStatus`. Same rationale as
/// [`ReloadCall`].
#[async_trait::async_trait]
pub(crate) trait GetRecording: Send + Sync {
    async fn is_recording(&self) -> Result<RecordingState, SettingsError>;
}

/// Concrete `Profiles1` client. The proxy is `None` when the bus
/// has no current owner of `cz.zajca.Zwhisper1`; in that state
/// every call short-circuits to `DaemonOff` without round-trip.
pub(crate) struct ProfilesClient {
    proxy: Option<Profiles1Proxy<'static>>,
}

impl ProfilesClient {
    /// Build a session-bus proxy. `ServiceUnknown` at construction
    /// time is mapped to `Self { proxy: None }` so the UI still
    /// boots when the daemon is offline.
    pub(crate) async fn connect() -> Result<Self, SettingsError> {
        let conn = zbus::Connection::session()
            .await
            .map_err(|e| SettingsError::Profile(format!("session bus: {e}")))?;
        match Profiles1Proxy::new(&conn).await {
            Ok(proxy) => Ok(Self { proxy: Some(proxy) }),
            Err(zbus::Error::FDO(boxed)) => {
                if matches!(*boxed, zbus::fdo::Error::ServiceUnknown(_)) {
                    debug!("Profiles1 service unknown; running in daemon-off mode");
                    Ok(Self { proxy: None })
                } else {
                    Err(SettingsError::Profile(format!("profiles proxy: {boxed}")))
                }
            }
            Err(other) => Err(SettingsError::Profile(format!("profiles proxy: {other}"))),
        }
    }
}

#[async_trait::async_trait]
impl ReloadCall for ProfilesClient {
    async fn reload(&self) -> Result<ReloadOutcome, SettingsError> {
        let Some(proxy) = self.proxy.as_ref() else {
            return Ok(ReloadOutcome::DaemonOff);
        };
        match proxy.reload().await {
            Ok(()) => Ok(ReloadOutcome::Reloaded),
            Err(e) => map_reload_error(&e),
        }
    }
}

/// Map a `zbus::Error` from `reload()` into either `DaemonOff` (the
/// daemon bus name is unclaimed) or a typed `SettingsError`. We
/// look at multiple error shapes because `ServiceUnknown` can be
/// reported as either `zbus::Error::FDO(ServiceUnknown)` or as a
/// remote method error with the canonical name.
fn map_reload_error(err: &zbus::Error) -> Result<ReloadOutcome, SettingsError> {
    if is_service_unknown(err) {
        debug!("Profiles1.reload: daemon offline (ServiceUnknown)");
        return Ok(ReloadOutcome::DaemonOff);
    }
    warn!(error = %err, "Profiles1.reload failed");
    Err(SettingsError::Profile(format!("reload: {err}")))
}

/// Detect the canonical `org.freedesktop.DBus.Error.ServiceUnknown`
/// across the two zbus error shapes we have observed in M3/M5.
fn is_service_unknown(err: &zbus::Error) -> bool {
    match err {
        zbus::Error::FDO(boxed) => matches!(**boxed, zbus::fdo::Error::ServiceUnknown(_)),
        zbus::Error::MethodError(name, _, _) => {
            name.as_str() == "org.freedesktop.DBus.Error.ServiceUnknown"
        }
        _ => false,
    }
}

/// Concrete `Recorder1` client.
pub(crate) struct RecorderClient {
    proxy: Option<Recorder1Proxy<'static>>,
}

impl RecorderClient {
    pub(crate) async fn connect() -> Result<Self, SettingsError> {
        let conn = zbus::Connection::session()
            .await
            .map_err(|e| SettingsError::Profile(format!("session bus: {e}")))?;
        match Recorder1Proxy::new(&conn).await {
            Ok(proxy) => Ok(Self { proxy: Some(proxy) }),
            Err(zbus::Error::FDO(boxed)) => {
                if matches!(*boxed, zbus::fdo::Error::ServiceUnknown(_)) {
                    debug!("Recorder1 service unknown; running in daemon-off mode");
                    Ok(Self { proxy: None })
                } else {
                    Err(SettingsError::Profile(format!("recorder proxy: {boxed}")))
                }
            }
            Err(other) => Err(SettingsError::Profile(format!("recorder proxy: {other}"))),
        }
    }
}

#[async_trait::async_trait]
impl GetRecording for RecorderClient {
    async fn is_recording(&self) -> Result<RecordingState, SettingsError> {
        let Some(proxy) = self.proxy.as_ref() else {
            return Ok(RecordingState::DaemonOff);
        };
        match proxy.get_status().await {
            Ok(status) => {
                if status.state == "recording" {
                    Ok(RecordingState::Recording)
                } else {
                    Ok(RecordingState::Idle)
                }
            }
            Err(e) if is_service_unknown(&e) => Ok(RecordingState::DaemonOff),
            Err(e) => {
                warn!(error = %e, "Recorder1.GetStatus failed");
                Err(SettingsError::Profile(format!("get_status: {e}")))
            }
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    /// Synthetic `zbus::Error` mimicking the FDO `ServiceUnknown`
    /// shape — used to verify the mapping path without a live bus.
    fn synth_service_unknown() -> zbus::Error {
        zbus::Error::FDO(Box::new(zbus::fdo::Error::ServiceUnknown(
            "no such service".into(),
        )))
    }

    #[test]
    fn service_unknown_detected_in_fdo_variant() {
        assert!(is_service_unknown(&synth_service_unknown()));
    }

    #[test]
    fn map_reload_error_returns_daemon_off_for_service_unknown() {
        let outcome = map_reload_error(&synth_service_unknown()).unwrap();
        assert_eq!(outcome, ReloadOutcome::DaemonOff);
    }

    #[test]
    fn map_reload_error_propagates_other_errors() {
        let other = zbus::Error::Address("not a real address".into());
        let result = map_reload_error(&other);
        assert!(matches!(result, Err(SettingsError::Profile(_))));
    }

    // ----- M8 ProtocolStatus enumeration tests (DoD #13) -----
    //
    // These pin the variant shapes that `main.rs` matches on. We
    // do not stand up a real D-Bus broker here — the variant
    // construction is what `probe_protocol` produces and what the
    // launch gate consumes, so a unit test is sufficient.

    #[test]
    fn protocol_status_match_is_distinct_from_daemon_off() {
        // Match and DaemonOff both let the GUI launch, but they
        // mean different things: Match → matched daemon online,
        // DaemonOff → no daemon to match against. The launch
        // path keys on this distinction for log output, so we
        // pin equality semantics.
        assert_ne!(ProtocolStatus::Match, ProtocolStatus::DaemonOff);
    }

    #[test]
    fn protocol_status_mismatch_carries_legacy_flag() {
        let real = ProtocolStatus::Mismatch {
            expected: "0.1.0".to_owned(),
            got: "0.0.99".to_owned(),
            legacy: false,
        };
        let legacy = ProtocolStatus::Mismatch {
            expected: "0.1.0".to_owned(),
            got: "pre-0.1.0".to_owned(),
            legacy: true,
        };
        assert_ne!(real, legacy);
        if let ProtocolStatus::Mismatch { legacy, .. } = legacy {
            assert!(legacy);
        } else {
            panic!("expected legacy mismatch variant");
        }
    }

    #[test]
    fn legacy_sentinel_value_lines_up_with_ipc_constant() {
        // The settings probe sets `got` to
        // `ProtocolMismatch::LEGACY_DAEMON_SENTINEL`. Pin the
        // value so a future rename in `zwhisper-ipc` trips the
        // test instead of producing a silent UI banner with the
        // wrong text.
        assert_eq!(
            zwhisper_ipc::ProtocolMismatch::LEGACY_DAEMON_SENTINEL,
            "pre-0.1.0"
        );
    }
}
