//! M7 — D-Bus client facades for the profile editor tab.
//!
//! These are thin typed wrappers over the proxies generated by
//! `zwhisper-ipc` (`Profiles1Proxy`, `Recorder1Proxy`). They exist
//! so the profile-tab logic can be unit-tested through small async
//! traits (`ReloadCall`, `GetRecording`) without spinning up a real
//! D-Bus broker.
//!
//! Both clients treat `ServiceUnknown` as the "daemon is offline"
//! case (M7-plan risk A4 / `DoD` `service_unknown_treated_as_daemon_off`)
//! rather than an error: the settings UI must remain usable even
//! when the daemon is not running, and the user simply gets a
//! "saved (will apply on next daemon start)" toast.
//!
//! Bus selection: session bus, mirroring the daemon (M3 lock-in).

// `ProfilesClient::connect` and `RecorderClient::connect` are
// constructed by `tabs::profile`'s save flow once Group D wires
// the live D-Bus path — until then the unit tests in this file
// (and in `tabs::profile`) are the only consumers, so clippy
// considers the helpers dead. See module doc for rationale.
#![allow(dead_code)]

use tracing::{debug, warn};
use zwhisper_ipc::{Profiles1Proxy, Recorder1Proxy};

use crate::error::SettingsError;

/// Outcome of a `Profiles1.reload` call. `DaemonOff` means the
/// well-known service name is unclaimed (`org.freedesktop.DBus.Error.ServiceUnknown`),
/// which the settings binary surfaces as a non-fatal toast rather
/// than a hard error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ReloadOutcome {
    Reloaded,
    DaemonOff,
}

/// Snapshot of the recorder state, simplified to a tri-state for
/// the save-during-recording prompt (`DoD` #3 / D6). Only the
/// `Recording` arm triggers the modal warning; transitional states
/// (`starting`, `stopping`, `failed`) and `Idle` are treated as
/// "safe to reload".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum RecordingState {
    Idle,
    Recording,
    DaemonOff,
}

/// Async port for `Profiles1.reload`. Lives as a trait so the save
/// logic in `tabs::profile` can be unit-tested with a fake that
/// records call counts without touching a live bus.
#[async_trait::async_trait]
pub(crate) trait ReloadCall: Send + Sync {
    async fn reload(&self) -> Result<ReloadOutcome, SettingsError>;
}

/// Async port for `Recorder1.GetStatus`. Same rationale as
/// [`ReloadCall`].
#[async_trait::async_trait]
pub(crate) trait GetRecording: Send + Sync {
    async fn is_recording(&self) -> Result<RecordingState, SettingsError>;
}

/// Concrete `Profiles1` client. The proxy is `None` when the bus
/// has no current owner of `cz.zajca.Zwhisper1`; in that state
/// every call short-circuits to `DaemonOff` without round-trip.
pub(crate) struct ProfilesClient {
    proxy: Option<Profiles1Proxy<'static>>,
}

impl ProfilesClient {
    /// Build a session-bus proxy. `ServiceUnknown` at construction
    /// time is mapped to `Self { proxy: None }` so the UI still
    /// boots when the daemon is offline.
    pub(crate) async fn connect() -> Result<Self, SettingsError> {
        let conn = zbus::Connection::session()
            .await
            .map_err(|e| SettingsError::Profile(format!("session bus: {e}")))?;
        match Profiles1Proxy::new(&conn).await {
            Ok(proxy) => Ok(Self { proxy: Some(proxy) }),
            Err(zbus::Error::FDO(boxed)) => {
                if matches!(*boxed, zbus::fdo::Error::ServiceUnknown(_)) {
                    debug!("Profiles1 service unknown; running in daemon-off mode");
                    Ok(Self { proxy: None })
                } else {
                    Err(SettingsError::Profile(format!("profiles proxy: {boxed}")))
                }
            }
            Err(other) => Err(SettingsError::Profile(format!(
                "profiles proxy: {other}"
            ))),
        }
    }
}

#[async_trait::async_trait]
impl ReloadCall for ProfilesClient {
    async fn reload(&self) -> Result<ReloadOutcome, SettingsError> {
        let Some(proxy) = self.proxy.as_ref() else {
            return Ok(ReloadOutcome::DaemonOff);
        };
        match proxy.reload().await {
            Ok(()) => Ok(ReloadOutcome::Reloaded),
            Err(e) => map_reload_error(&e),
        }
    }
}

/// Map a `zbus::Error` from `reload()` into either `DaemonOff` (the
/// daemon bus name is unclaimed) or a typed `SettingsError`. We
/// look at multiple error shapes because `ServiceUnknown` can be
/// reported as either `zbus::Error::FDO(ServiceUnknown)` or as a
/// remote method error with the canonical name.
fn map_reload_error(err: &zbus::Error) -> Result<ReloadOutcome, SettingsError> {
    if is_service_unknown(err) {
        debug!("Profiles1.reload: daemon offline (ServiceUnknown)");
        return Ok(ReloadOutcome::DaemonOff);
    }
    warn!(error = %err, "Profiles1.reload failed");
    Err(SettingsError::Profile(format!("reload: {err}")))
}

/// Detect the canonical `org.freedesktop.DBus.Error.ServiceUnknown`
/// across the two zbus error shapes we have observed in M3/M5.
fn is_service_unknown(err: &zbus::Error) -> bool {
    match err {
        zbus::Error::FDO(boxed) => matches!(**boxed, zbus::fdo::Error::ServiceUnknown(_)),
        zbus::Error::MethodError(name, _, _) => {
            name.as_str() == "org.freedesktop.DBus.Error.ServiceUnknown"
        }
        _ => false,
    }
}

/// Concrete `Recorder1` client.
pub(crate) struct RecorderClient {
    proxy: Option<Recorder1Proxy<'static>>,
}

impl RecorderClient {
    pub(crate) async fn connect() -> Result<Self, SettingsError> {
        let conn = zbus::Connection::session()
            .await
            .map_err(|e| SettingsError::Profile(format!("session bus: {e}")))?;
        match Recorder1Proxy::new(&conn).await {
            Ok(proxy) => Ok(Self { proxy: Some(proxy) }),
            Err(zbus::Error::FDO(boxed)) => {
                if matches!(*boxed, zbus::fdo::Error::ServiceUnknown(_)) {
                    debug!("Recorder1 service unknown; running in daemon-off mode");
                    Ok(Self { proxy: None })
                } else {
                    Err(SettingsError::Profile(format!("recorder proxy: {boxed}")))
                }
            }
            Err(other) => Err(SettingsError::Profile(format!(
                "recorder proxy: {other}"
            ))),
        }
    }
}

#[async_trait::async_trait]
impl GetRecording for RecorderClient {
    async fn is_recording(&self) -> Result<RecordingState, SettingsError> {
        let Some(proxy) = self.proxy.as_ref() else {
            return Ok(RecordingState::DaemonOff);
        };
        match proxy.get_status().await {
            Ok(status) => {
                if status.state == "recording" {
                    Ok(RecordingState::Recording)
                } else {
                    Ok(RecordingState::Idle)
                }
            }
            Err(e) if is_service_unknown(&e) => Ok(RecordingState::DaemonOff),
            Err(e) => {
                warn!(error = %e, "Recorder1.GetStatus failed");
                Err(SettingsError::Profile(format!("get_status: {e}")))
            }
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    /// Synthetic `zbus::Error` mimicking the FDO `ServiceUnknown`
    /// shape — used to verify the mapping path without a live bus.
    fn synth_service_unknown() -> zbus::Error {
        zbus::Error::FDO(Box::new(zbus::fdo::Error::ServiceUnknown(
            "no such service".into(),
        )))
    }

    #[test]
    fn service_unknown_detected_in_fdo_variant() {
        assert!(is_service_unknown(&synth_service_unknown()));
    }

    #[test]
    fn map_reload_error_returns_daemon_off_for_service_unknown() {
        let outcome = map_reload_error(&synth_service_unknown()).unwrap();
        assert_eq!(outcome, ReloadOutcome::DaemonOff);
    }

    #[test]
    fn map_reload_error_propagates_other_errors() {
        let other = zbus::Error::Address("not a real address".into());
        let result = map_reload_error(&other);
        assert!(matches!(result, Err(SettingsError::Profile(_))));
    }
}
