version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Prague
    open-pull-requests-limit: 5
    groups:
      tracing:
        patterns:
          - "tracing*"
      clap:
        patterns:
          - "clap*"
      dev-deps:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "06:00"
      timezone: Europe/Prague
    open-pull-requests-limit: 5
